/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Exact color map from code.html
        "surface": "#fffcf2",
        "surface-bright": "#fffcf2",
        "secondary-dim": "#764c5c",
        "tertiary-fixed": "#fbc1de",
        "background": "#fffcf2",
        "on-primary-fixed": "#55002b",
        "surface-container-highest": "#e9ead2",
        "surface-tint": "#b52d6b",
        "tertiary-container": "#fbc1de",
        "tertiary-fixed-dim": "#ecb4d0",
        "on-secondary-fixed-variant": "#794f5f",
        "secondary": "#835868",
        "on-primary-fixed-variant": "#8b004b",
        "on-tertiary-fixed-variant": "#6f435b",
        "surface-container": "#f5f4e4",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#fcc6d9",
        "on-error": "#ffffff",
        "surface-container-high": "#efefdb",
        "on-error-container": "#68001f",
        "primary-fixed": "#ffa8c4",
        "outline-variant": "#b9bba5",
        "on-surface": "#373929",
        "surface-variant": "#e9ead2",
        "on-tertiary": "#ffffff",
        "primary-dim": "#a51f5e",
        "on-primary": "#ffffff",
        "inverse-primary": "#f963a0",
        "on-background": "#373929",
        "surface-dim": "#e2e5c9",
        "secondary-fixed": "#ffd9e5",
        "inverse-surface": "#0e0f09",
        "tertiary-dim": "#774b62",
        "surface-container-low": "#fbfaed",
        "error-dim": "#770326",
        "on-primary-container": "#7b0041",
        "error": "#b3374e",
        "inverse-on-surface": "#9e9d94",
        "primary-fixed-dim": "#ff92b8",
        "on-secondary-fixed": "#5a3443",
        "on-surface-variant": "#646653",
        "outline": "#80826e",
        "error-container": "#f76a80",
        "primary-container": "#ffa8c4",
        "tertiary": "#85566f",
        "secondary-container": "#ffd9e5",
        "on-tertiary-fixed": "#4f273e",
        "on-secondary-container": "#6e4655",
        "primary": "#b52d6b",
        "on-tertiary-container": "#643a51",
        // Additional aliases
        "text-primary": "#1A0010",
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px",
      },
      fontFamily: {
        "headline": ["Cormorant Garamond", "serif"],
        "display": ["Cormorant Garamond", "serif"],
        "body": ["DM Sans", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
        "accent": ["Cookie", "cursive"],
        "editorial": ["Newsreader", "serif"],
      },
    },
  },
  plugins: [],
}
